<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Badawi Amin Muhammed">
<meta name="dcterms.date" content="2026-07-04">

<title>Global Spatial Analysis of Childhood Stunting</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Global_stunting_files/libs/clipboard/clipboard.min.js"></script>
<script src="Global_stunting_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Global_stunting_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Global_stunting_files/libs/quarto-html/popper.min.js"></script>
<script src="Global_stunting_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Global_stunting_files/libs/quarto-html/anchor.min.js"></script>
<link href="Global_stunting_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Global_stunting_files/libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Global_stunting_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Global_stunting_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Global_stunting_files/libs/bootstrap/bootstrap-813c323200a87c37e262811031999de4.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a></li>
  <li><a href="#objectives" id="toc-objectives" class="nav-link" data-scroll-target="#objectives"><span class="header-section-number">2</span> Objectives</a></li>
  <li><a href="#import-data" id="toc-import-data" class="nav-link" data-scroll-target="#import-data"><span class="header-section-number">3</span> Import Data</a></li>
  <li><a href="#data-quality-assessment" id="toc-data-quality-assessment" class="nav-link" data-scroll-target="#data-quality-assessment"><span class="header-section-number">4</span> Data Quality Assessment</a></li>
  <li><a href="#join-spatial-data" id="toc-join-spatial-data" class="nav-link" data-scroll-target="#join-spatial-data"><span class="header-section-number">5</span> Join Spatial Data</a></li>
  <li><a href="#exploratory-data-analysis" id="toc-exploratory-data-analysis" class="nav-link" data-scroll-target="#exploratory-data-analysis"><span class="header-section-number">6</span> Exploratory Data Analysis</a>
  <ul class="collapse">
  <li><a href="#descriptive-statistics" id="toc-descriptive-statistics" class="nav-link" data-scroll-target="#descriptive-statistics"><span class="header-section-number">6.1</span> Descriptive Statistics</a>
  <ul class="collapse">
  <li><a href="#countries-with-exceptionally-high-stunting-prevalence" id="toc-countries-with-exceptionally-high-stunting-prevalence" class="nav-link" data-scroll-target="#countries-with-exceptionally-high-stunting-prevalence"><span class="header-section-number">6.1.1</span> Countries with Exceptionally High Stunting Prevalence</a></li>
  </ul></li>
  <li><a href="#countries-with-the-highest-and-lowest-childhood-stunting-prevalence" id="toc-countries-with-the-highest-and-lowest-childhood-stunting-prevalence" class="nav-link" data-scroll-target="#countries-with-the-highest-and-lowest-childhood-stunting-prevalence"><span class="header-section-number">6.2</span> Countries with the Highest and Lowest Childhood Stunting Prevalence</a></li>
  </ul></li>
  <li><a href="#countries-with-the-highest-stunting-prevalence" id="toc-countries-with-the-highest-stunting-prevalence" class="nav-link" data-scroll-target="#countries-with-the-highest-stunting-prevalence"><span class="header-section-number">7</span> Countries with the Highest Stunting Prevalence</a></li>
  <li><a href="#global-distribution-of-childhood-stunting" id="toc-global-distribution-of-childhood-stunting" class="nav-link" data-scroll-target="#global-distribution-of-childhood-stunting"><span class="header-section-number">8</span> Global Distribution of Childhood Stunting</a></li>
  <li><a href="#classification-of-childhood-stunting-prevalence" id="toc-classification-of-childhood-stunting-prevalence" class="nav-link" data-scroll-target="#classification-of-childhood-stunting-prevalence"><span class="header-section-number">9</span> Classification of Childhood Stunting Prevalence</a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results"><span class="header-section-number">10</span> Results</a></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion"><span class="header-section-number">11</span> Discussion</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="header-section-number">12</span> Conclusion</a></li>
  <li><a href="#recommendations" id="toc-recommendations" class="nav-link" data-scroll-target="#recommendations"><span class="header-section-number">13</span> Recommendations</a></li>
  <li><a href="#appendix" id="toc-appendix" class="nav-link" data-scroll-target="#appendix"><span class="header-section-number">14</span> Appendix</a>
  <ul class="collapse">
  <li><a href="#reproducibility-information" id="toc-reproducibility-information" class="nav-link" data-scroll-target="#reproducibility-information"><span class="header-section-number">14.1</span> Reproducibility Information</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Global Spatial Analysis of Childhood Stunting</h1>
<p class="subtitle lead">A Reproducible GIS Analysis in R</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Badawi Amin Muhammed </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 4, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introduction</h1>
<p>Childhood stunting (low-height-for age resulting from chronic undernutrition during the first 1,000 days of life) remains one of the most important indicators of chronic undernutrition and poor child health worldwide. It reflects prolonged nutritional deprivation during critical stages of growth and is associated with impaired physical development, reduced cognitive performance, lower educational attainment, and diminished economic productivit</p>
<p>Understanding the geographical distribution of stunting is essential for identifying areas with a greater nutritional burden and supporting evidence-based public health planning. Geographic Information Systems (GIS) provide an effective approach for visualising spatial patterns and communicating health disparities in an intuitive manner.</p>
<p>This project presents a reproducible workflow in R for analysing and mapping country-level childhood stunting prevalence using descriptive statistics and spatial visualisation techniques.</p>
</section>
<section id="objectives" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Objectives</h1>
<p>The objectives of this analysis are to:</p>
<ul>
<li>describe the distribution of growth stunting across countries;</li>
<li>summarise the prevalence using descriptive statistics;</li>
<li>identify countries with the highest and lowest prevalence;</li>
<li>visualise the spatial distribution of stunting using GIS; and</li>
<li>demonstrate a reproducible geospatial workflow in R using Quarto.</li>
</ul>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load Packages</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(viridis)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(scales)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="import-data" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Import Data</h1>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Import stunting dataset</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>stunting <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"C:/Users/hp/Desktop/Global_Stunting_GIS/data/stunting_data.xlsx"</span>) <span class="sc">|&gt;</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">clean_names</span>()</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Import world shapefile</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>world <span class="ot">&lt;-</span> <span class="fu">st_read</span>(</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"C:/Users/hp/Desktop/Global_Stunting_GIS/ne_10m_admin_0_countries.shp"</span>,</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">quiet =</span> <span class="cn">TRUE</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert stunting to numeric</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>stunting<span class="sc">$</span>stunting <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(stunting<span class="sc">$</span>stunting)</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Data Overview</span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(stunting)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 162
Columns: 3
$ iso_code &lt;chr&gt; "AFG", "AGO", "ALB", "ARG", "ARM", "AUS", "AZE", "BDI", "BEL"…
$ country  &lt;chr&gt; "Afghanistan", "Angola", "Albania", "Argentina", "Armenia", "…
$ stunting &lt;dbl&gt; 42.0, 47.7, 7.4, 10.7, 6.2, 3.1, 6.8, 55.3, 2.6, 33.2, 19.5, …</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(stunting)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  iso_code country     stunting
  &lt;chr&gt;    &lt;chr&gt;          &lt;dbl&gt;
1 AFG      Afghanistan     42  
2 AGO      Angola          47.7
3 ALB      Albania          7.4
4 ARG      Argentina       10.7
5 ARM      Armenia          6.2
6 AUS      Australia        3.1</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(stunting)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   iso_code           country             stunting    
 Length:162         Length:162         Min.   : 1.00  
 Class :character   Class :character   1st Qu.: 5.90  
 Mode  :character   Mode  :character   Median :11.70  
                                       Mean   :16.15  
                                       3rd Qu.:24.20  
                                       Max.   :55.30  </code></pre>
</div>
</div>
</section>
<section id="data-quality-assessment" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Data Quality Assessment</h1>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colSums</span>(<span class="fu">is.na</span>(stunting))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>iso_code  country stunting 
       0        0        0 </code></pre>
</div>
</div>
<p><strong>Interpretation</strong></p>
<p>The data quality assessment indicates that there are no missing values in any of the three variables (<code>iso_code</code>, <code>country</code>, and <code>stunting</code>). This confirms that the dataset is complete and suitable for descriptive statistical analysis and spatial visualisation without requiring data imputation or removal of incomplete records.</p>
<p>Ensuring data completeness at this stage improves the reliability of subsequent analyses and minimises the risk of biased statistical summaries or incomplete geographic representations.</p>
</section>
<section id="join-spatial-data" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Join Spatial Data</h1>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>map_data <span class="ot">&lt;-</span> world <span class="sc">|&gt;</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(stunting,</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"ADM0_A3"</span> <span class="ot">=</span> <span class="st">"iso_code"</span>))</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(map_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 258</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(map_data<span class="sc">$</span>stunting))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 98</code></pre>
</div>
</div>
<p><strong>Interpretation</strong></p>
<p>Verification of the spatial join showed that <strong>98</strong> polygons did not have corresponding childhood stunting data. This result was expected because the Natural Earth world shapefile contains additional geographic entities, including overseas territories, dependencies and disputed areas, whereas the analytical dataset includes <strong>162 sovereign countries</strong>.</p>
<p>The unmatched polygons are displayed as missing values (<code>NA</code>) and appear in grey on the thematic maps. Their presence does not indicate an error in the analysis but rather reflects differences in coverage between the spatial boundary dataset and the country-level health dataset.</p>
<p>Overall, the verification confirms that the spatial join was successfully completed and that the resulting dataset is appropriate for subsequent GIS visualisation.</p>
</section>
<section id="exploratory-data-analysis" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Exploratory Data Analysis</h1>
<section id="descriptive-statistics" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="descriptive-statistics"><span class="header-section-number">6.1</span> Descriptive Statistics</h2>
<p>Before producing maps, it is important to understand the statistical characteristics of the dataset. Descriptive statistics provide a concise summary of the central tendency and variability of childhood stunting prevalence across countries.</p>
<p>This preliminary analysis helps identify the typical prevalence level, the degree of variation between countries, and any unusually high or low observations that may influence interpretation of subsequent visualisations.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>summary_stats <span class="ot">&lt;-</span> stunting <span class="sc">|&gt;</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">Countries =</span> <span class="fu">n</span>(),</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">Mean =</span> <span class="fu">mean</span>(stunting),</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">Median =</span> <span class="fu">median</span>(stunting),</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">Minimum =</span> <span class="fu">min</span>(stunting),</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">Maximum =</span> <span class="fu">max</span>(stunting),</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">Standard_Deviation =</span> <span class="fu">sd</span>(stunting),</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">Variance =</span> <span class="fu">var</span>(stunting),</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">Q1 =</span> <span class="fu">quantile</span>(stunting, <span class="fl">0.25</span>),</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">Q3 =</span> <span class="fu">quantile</span>(stunting, <span class="fl">0.75</span>),</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">IQR =</span> <span class="fu">IQR</span>(stunting)</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(summary_stats, <span class="at">digits =</span> <span class="dv">2</span>,</span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">"Table 1. Summary statistics of childhood stunting prevalence."</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Table 1. Summary statistics of childhood stunting prevalence.</caption>
<colgroup>
<col style="width: 12%">
<col style="width: 7%">
<col style="width: 8%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 23%">
<col style="width: 11%">
<col style="width: 4%">
<col style="width: 6%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Countries</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">Median</th>
<th style="text-align: right;">Minimum</th>
<th style="text-align: right;">Maximum</th>
<th style="text-align: right;">Standard_Deviation</th>
<th style="text-align: right;">Variance</th>
<th style="text-align: right;">Q1</th>
<th style="text-align: right;">Q3</th>
<th style="text-align: right;">IQR</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">162</td>
<td style="text-align: right;">16.15</td>
<td style="text-align: right;">11.7</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">55.3</td>
<td style="text-align: right;">12.8</td>
<td style="text-align: right;">163.87</td>
<td style="text-align: right;">5.9</td>
<td style="text-align: right;">24.2</td>
<td style="text-align: right;">18.3</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Interpretation</strong></p>
<p>The dataset comprised <strong>162 countries</strong>, with childhood stunting prevalence ranging from <strong>1.0%</strong> to <strong>55.3%</strong>. The mean prevalence was <strong>16.2%</strong>, while the median was <strong>11.7%</strong>, indicating that half of the countries reported stunting levels below approximately 12%.</p>
<p>The difference between the mean and the median suggests that the distribution is positively skewed, with a relatively small number of countries exhibiting substantially higher prevalence than the majority. This observation is supported by the maximum prevalence of <strong>55.3%</strong>, which is considerably higher than both the average and the upper quartile.</p>
<p>The interquartile range (IQR) of <strong>18.3 percentage points</strong> indicates moderate variability among the middle 50% of countries, while the standard deviation of <strong>12.8 percentage points</strong> reflects considerable differences in childhood stunting prevalence across countries. Overall, these descriptive statistics suggest substantial global variation in childhood nutritional outcomes.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate mean and median for reference lines</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>mean_stunting <span class="ot">&lt;-</span> <span class="fu">mean</span>(stunting<span class="sc">$</span>stunting)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>median_stunting <span class="ot">&lt;-</span> <span class="fu">median</span>(stunting<span class="sc">$</span>stunting)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Create histogram</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(stunting, <span class="fu">aes</span>(<span class="at">x =</span> stunting)) <span class="sc">+</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">bins =</span> <span class="dv">20</span>,</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"#2C7FB8"</span>,</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">colour =</span> <span class="st">"white"</span></span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(</span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">xintercept =</span> mean_stunting,</span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">colour =</span> <span class="st">"red"</span>,</span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">linewidth =</span> <span class="dv">1</span>,</span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">linetype =</span> <span class="st">"dashed"</span></span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(</span>
<span id="cb15-23"><a href="#cb15-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">xintercept =</span> median_stunting,</span>
<span id="cb15-24"><a href="#cb15-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">colour =</span> <span class="st">"darkgreen"</span>,</span>
<span id="cb15-25"><a href="#cb15-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">linewidth =</span> <span class="dv">1</span>,</span>
<span id="cb15-26"><a href="#cb15-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">linetype =</span> <span class="st">"dashed"</span></span>
<span id="cb15-27"><a href="#cb15-27" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb15-28"><a href="#cb15-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-29"><a href="#cb15-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb15-30"><a href="#cb15-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Distribution of Childhood Stunting Prevalence"</span>,</span>
<span id="cb15-31"><a href="#cb15-31" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Country-level prevalence across 162 countries"</span>,</span>
<span id="cb15-32"><a href="#cb15-32" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Stunting prevalence (%)"</span>,</span>
<span id="cb15-33"><a href="#cb15-33" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Number of countries"</span>,</span>
<span id="cb15-34"><a href="#cb15-34" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"Red dashed line = Mean | Green dashed line = Median"</span></span>
<span id="cb15-35"><a href="#cb15-35" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb15-36"><a href="#cb15-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-37"><a href="#cb15-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">13</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Global_stunting_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation</strong></p>
<p>The histogram illustrates the frequency distribution of stunting prevalence across the 162 countries included in the analysis. Most countries reported relatively low to moderate prevalence, with observations concentrated below 25%.</p>
<p>The mean prevalence (red dashed line) is positioned to the right of the median (green dashed line), indicating a positively skewed distribution. This suggests that although many countries experience comparatively low levels of childhood stunting, a smaller number of countries exhibit substantially higher prevalence, increasing the overall average.</p>
<p>The distribution demonstrates considerable variability, reflecting marked differences in childhood nutritional outcomes between countries.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(stunting, <span class="fu">aes</span>(<span class="at">y =</span> stunting)) <span class="sc">+</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"#66C2A5"</span>,</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">colour =</span> <span class="st">"black"</span>,</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">width =</span> <span class="fl">0.35</span>,</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">outlier.colour =</span> <span class="st">"red"</span>,</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">outlier.size =</span> <span class="dv">3</span></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Boxplot of Childhood Stunting Prevalence"</span>,</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Distribution across 162 countries"</span>,</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Stunting prevalence (%)"</span>,</span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="cn">NULL</span></span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">13</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Global_stunting_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation</strong></p>
<p>The boxplot confirms the variability observed in the descriptive statistics while providing additional insight into the presence of extreme observations. The median prevalence is located closer to the lower quartile than the upper quartile, reflecting the positively skewed distribution identified in the histogram.</p>
<section id="countries-with-exceptionally-high-stunting-prevalence" class="level3" data-number="6.1.1">
<h3 data-number="6.1.1" class="anchored" data-anchor-id="countries-with-exceptionally-high-stunting-prevalence"><span class="header-section-number">6.1.1</span> Countries with Exceptionally High Stunting Prevalence</h3>
<p>To complement the boxplot, countries with stunting prevalence exceeding the upper whisker are identified below. These observations represent unusually high prevalence relative to the overall distribution and may warrant additional public health attention.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>Q1 <span class="ot">&lt;-</span> <span class="fu">quantile</span>(stunting<span class="sc">$</span>stunting, <span class="fl">0.25</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>Q3 <span class="ot">&lt;-</span> <span class="fu">quantile</span>(stunting<span class="sc">$</span>stunting, <span class="fl">0.75</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>IQR_value <span class="ot">&lt;-</span> <span class="fu">IQR</span>(stunting<span class="sc">$</span>stunting)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>upper_limit <span class="ot">&lt;-</span> Q3 <span class="sc">+</span> <span class="fl">1.5</span> <span class="sc">*</span> IQR_value</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>outliers <span class="ot">&lt;-</span> stunting <span class="sc">|&gt;</span></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(stunting <span class="sc">&gt;</span> upper_limit) <span class="sc">|&gt;</span></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(stunting))</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>  outliers,</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">"Table 2. Countries identified as potential high-prevalence outliers."</span></span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Table 2. Countries identified as potential high-prevalence outliers.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">iso_code</th>
<th style="text-align: left;">country</th>
<th style="text-align: right;">stunting</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">BDI</td>
<td style="text-align: left;">Burundi</td>
<td style="text-align: right;">55.3</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Interpretation</strong></p>
<p>Using the conventional 1.5 × IQR criterion, only <strong>Burundi</strong> was identified as a potential statistical outlier, with a reported childhood stunting prevalence of <strong>55.3%</strong>. This indicates that although several countries experience relatively high prevalence, only one country exhibits a value that is substantially higher than the remainder of the dataset.</p>
<p>The identification of Burundi as an outlier should not be interpreted as an error in the data. Rather, it represents an observation that differs markedly from the overall global distribution and highlights a country where childhood undernutrition may be particularly severe.</p>
</section>
</section>
<section id="countries-with-the-highest-and-lowest-childhood-stunting-prevalence" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="countries-with-the-highest-and-lowest-childhood-stunting-prevalence"><span class="header-section-number">6.2</span> Countries with the Highest and Lowest Childhood Stunting Prevalence</h2>
<p>To better understand the global distribution of childhood stunting, countries are ranked according to their reported prevalence. The following tables present the ten countries with the highest prevalence and the ten countries with the lowest prevalence.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>top10 <span class="ot">&lt;-</span> stunting <span class="sc">|&gt;</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(stunting)) <span class="sc">|&gt;</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">10</span>)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>bottom10 <span class="ot">&lt;-</span> stunting <span class="sc">|&gt;</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(stunting) <span class="sc">|&gt;</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">10</span>)</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>  top10,</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">"Table 3. Ten countries with the highest childhood stunting prevalence."</span></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Table 3. Ten countries with the highest childhood stunting prevalence.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">iso_code</th>
<th style="text-align: left;">country</th>
<th style="text-align: right;">stunting</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">BDI</td>
<td style="text-align: left;">Burundi</td>
<td style="text-align: right;">55.3</td>
</tr>
<tr class="even">
<td style="text-align: left;">NER</td>
<td style="text-align: left;">Niger</td>
<td style="text-align: right;">48.3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ERI</td>
<td style="text-align: left;">Eritrea</td>
<td style="text-align: right;">48.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">AGO</td>
<td style="text-align: left;">Angola</td>
<td style="text-align: right;">47.7</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PNG</td>
<td style="text-align: left;">Papua New Guinea</td>
<td style="text-align: right;">47.6</td>
</tr>
<tr class="even">
<td style="text-align: left;">YEM</td>
<td style="text-align: left;">Yemen</td>
<td style="text-align: right;">47.4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">TLS</td>
<td style="text-align: left;">Timor-Leste</td>
<td style="text-align: right;">45.4</td>
</tr>
<tr class="even">
<td style="text-align: left;">GTM</td>
<td style="text-align: left;">Guatemala</td>
<td style="text-align: right;">44.6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">COD</td>
<td style="text-align: left;">Democratic Republic of the Congo</td>
<td style="text-align: right;">44.1</td>
</tr>
<tr class="even">
<td style="text-align: left;">AFG</td>
<td style="text-align: left;">Afghanistan</td>
<td style="text-align: right;">42.0</td>
</tr>
</tbody>
</table>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  bottom10,</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">"Table 4. Ten countries with the lowest childhood stunting prevalence."</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Table 4. Ten countries with the lowest childhood stunting prevalence.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">iso_code</th>
<th style="text-align: left;">country</th>
<th style="text-align: right;">stunting</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">POL</td>
<td style="text-align: left;">Poland</td>
<td style="text-align: right;">1.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">BLR</td>
<td style="text-align: left;">Belarus</td>
<td style="text-align: right;">1.1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EST</td>
<td style="text-align: left;">Estonia</td>
<td style="text-align: right;">1.3</td>
</tr>
<tr class="even">
<td style="text-align: left;">LTU</td>
<td style="text-align: left;">Lithuania</td>
<td style="text-align: right;">1.6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">NLD</td>
<td style="text-align: left;">Netherlands (Kingdom of the)</td>
<td style="text-align: right;">1.6</td>
</tr>
<tr class="even">
<td style="text-align: left;">TON</td>
<td style="text-align: left;">Tonga</td>
<td style="text-align: right;">1.6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CHL</td>
<td style="text-align: left;">Chile</td>
<td style="text-align: right;">1.7</td>
</tr>
<tr class="even">
<td style="text-align: left;">FIN</td>
<td style="text-align: left;">Finland</td>
<td style="text-align: right;">1.7</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LVA</td>
<td style="text-align: left;">Latvia</td>
<td style="text-align: right;">1.7</td>
</tr>
<tr class="even">
<td style="text-align: left;">KOR</td>
<td style="text-align: left;">Republic of Korea</td>
<td style="text-align: right;">1.8</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Interpretation</strong></p>
<p>Ranking countries according to childhood stunting prevalence reveals substantial disparities across the 162 countries analysed. The highest recorded prevalence exceeded 50%, whereas the lowest prevalence was approximately 1%, demonstrating a difference of more than fifty percentage points between countries.</p>
<p>Burundi recorded the highest childhood stunting prevalence (55.3%), making it the most extreme observation in the dataset. In contrast, Poland reported the lowest prevalence (1.0%), followed by several European countries with prevalence below 2%.</p>
<p>The countries with the lowest prevalence are predominantly high-income nations, while the highest-prevalence countries are concentrated among low- and middle-income settings. Although this analysis is descriptive and does not investigate causal relationships, the rankings highlight considerable global inequalities in childhood nutritional outcomes and provide important context for the spatial analysis presented in the following sections.</p>
</section>
</section>
<section id="countries-with-the-highest-stunting-prevalence" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Countries with the Highest Stunting Prevalence</h1>
<p>To facilitate comparison between countries with the greatest burden of childhood stunting, the fifteen highest-prevalence countries are visualised using a horizontal bar chart. Ordering the bars from highest to lowest prevalence improves readability and highlights the magnitude of differences between countries.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>top15 <span class="ot">&lt;-</span> stunting <span class="sc">|&gt;</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(stunting)) <span class="sc">|&gt;</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">15</span>)</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  top15,</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="fu">reorder</span>(country, stunting),</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> stunting</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_col</span>(<span class="at">fill =</span> <span class="st">"#D73027"</span>) <span class="sc">+</span></span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a><span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_text</span>(</span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">label =</span> stunting),</span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">hjust =</span> <span class="sc">-</span><span class="fl">0.2</span>,</span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">size =</span> <span class="fl">3.8</span></span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-23"><a href="#cb20-23" aria-hidden="true" tabindex="-1"></a><span class="fu">labs</span>(</span>
<span id="cb20-24"><a href="#cb20-24" aria-hidden="true" tabindex="-1"></a>  <span class="at">title =</span> <span class="st">"Top 15 Countries by Childhood Stunting Prevalence"</span>,</span>
<span id="cb20-25"><a href="#cb20-25" aria-hidden="true" tabindex="-1"></a>  <span class="at">subtitle =</span> <span class="st">"Country-level prevalence (%)"</span>,</span>
<span id="cb20-26"><a href="#cb20-26" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> <span class="cn">NULL</span>,</span>
<span id="cb20-27"><a href="#cb20-27" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> <span class="st">"Stunting prevalence (%)"</span></span>
<span id="cb20-28"><a href="#cb20-28" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb20-29"><a href="#cb20-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-30"><a href="#cb20-30" aria-hidden="true" tabindex="-1"></a><span class="fu">expand_limits</span>(<span class="at">y =</span> <span class="dv">60</span>) <span class="sc">+</span></span>
<span id="cb20-31"><a href="#cb20-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-32"><a href="#cb20-32" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">13</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Global_stunting_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation</strong></p>
<p>The ranked bar chart provides a clear visual comparison of the countries with the highest childhood stunting prevalence. Burundi recorded the highest prevalence (55.3%), followed by Niger, Eritrea, Angola and Papua New Guinea, all of which reported substantially higher prevalence than the global average of 16.2%.</p>
<p>The differences in bar lengths illustrate the considerable variation in childhood stunting among the highest-burden countries. Although these countries are located in different geographic regions, they share comparatively high levels of childhood undernutrition relative to the remainder of the dataset.</p>
<p>The figure complements the descriptive statistics by demonstrating that the overall positive skewness of the dataset is driven by a relatively small number of countries with exceptionally high prevalence.</p>
</section>
<section id="global-distribution-of-childhood-stunting" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Global Distribution of Childhood Stunting</h1>
<p>Understanding the geographical distribution of childhood stunting is essential for identifying areas with relatively high and low nutritional burden. A choropleth map displays the prevalence of childhood stunting by country, allowing spatial patterns to be explored visually.</p>
<p>The map below joins the country-level prevalence data to a global administrative boundary dataset using ISO 3166-1 Alpha-3 country codes. Countries for which no prevalence data are available are displayed in light grey.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(map_data) <span class="sc">+</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_sf</span>(</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">fill =</span> stunting),</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">colour =</span> <span class="st">"white"</span>,</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">linewidth =</span> <span class="fl">0.1</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a><span class="fu">scale_fill_viridis_c</span>(</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">option =</span> <span class="st">"plasma"</span>,</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">na.value =</span> <span class="st">"grey90"</span>,</span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">name =</span> <span class="st">"Stunting (%)"</span></span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a><span class="fu">labs</span>(</span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Global Distribution of Childhood Stunting"</span>,</span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Country-level prevalence across 162 countries"</span>,</span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"Grey countries indicate that no data were available."</span></span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb21-20"><a href="#cb21-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-21"><a href="#cb21-21" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">13</span>) <span class="sc">+</span></span>
<span id="cb21-22"><a href="#cb21-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-23"><a href="#cb21-23" aria-hidden="true" tabindex="-1"></a><span class="fu">theme</span>(</span>
<span id="cb21-24"><a href="#cb21-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.position =</span> <span class="st">"right"</span>,</span>
<span id="cb21-25"><a href="#cb21-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb21-26"><a href="#cb21-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.text =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb21-27"><a href="#cb21-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_blank</span>()</span>
<span id="cb21-28"><a href="#cb21-28" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Global_stunting_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation</strong></p>
<p>The choropleth map reveals marked geographical variation in childhood stunting prevalence across the 162 countries included in the analysis. Countries in North America, much of South America, Australia, and several parts of Europe generally exhibited lower prevalence, as indicated by the darker blue colours corresponding to values below approximately 20%.</p>
<p>In contrast, relatively higher prevalence was observed across several countries in West, Central, Eastern and Southern Africa, where many countries recorded prevalence between 30% and 50%. Additional high-prevalence countries were also observed outside Africa, including parts of Asia and Oceania.</p>
<p>Overall, the map demonstrates that childhood stunting is not distributed uniformly across the world but instead exhibits distinct geographical clustering. These spatial patterns suggest that the burden of childhood undernutrition is concentrated in particular regions rather than being evenly distributed across countries.</p>
</section>
<section id="classification-of-childhood-stunting-prevalence" class="level1" data-number="9">
<h1 data-number="9"><span class="header-section-number">9</span> Classification of Childhood Stunting Prevalence</h1>
<p>While continuous colour scales effectively display variation in prevalence, public health reporting often benefits from categorising observations into meaningful groups. Classification simplifies interpretation by grouping countries with similar prevalence levels into distinct categories.</p>
<p>The following categories were defined for descriptive purposes:</p>
<ul>
<li><strong>Very Low:</strong> less than 10%</li>
<li><strong>Low:</strong> 10–19.9%</li>
<li><strong>Moderate:</strong> 20–29.9%</li>
<li><strong>High:</strong> 30–39.9%</li>
<li><strong>Very High:</strong> 40% or greater</li>
</ul>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>map_data <span class="ot">&lt;-</span> map_data <span class="sc">|&gt;</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">category =</span> <span class="fu">case_when</span>(</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>      stunting <span class="sc">&lt;</span> <span class="dv">10</span> <span class="sc">~</span> <span class="st">"Very Low"</span>,</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>      stunting <span class="sc">&lt;</span> <span class="dv">20</span> <span class="sc">~</span> <span class="st">"Low"</span>,</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>      stunting <span class="sc">&lt;</span> <span class="dv">30</span> <span class="sc">~</span> <span class="st">"Moderate"</span>,</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>      stunting <span class="sc">&lt;</span> <span class="dv">40</span> <span class="sc">~</span> <span class="st">"High"</span>,</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>      stunting <span class="sc">&gt;=</span> <span class="dv">40</span> <span class="sc">~</span> <span class="st">"Very High"</span>,</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="cn">NA_character_</span></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(map_data) <span class="sc">+</span></span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_sf</span>(</span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">fill =</span> category),</span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">colour =</span> <span class="st">"white"</span>,</span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">linewidth =</span> <span class="fl">0.1</span></span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-21"><a href="#cb22-21" aria-hidden="true" tabindex="-1"></a><span class="fu">scale_fill_manual</span>(</span>
<span id="cb22-22"><a href="#cb22-22" aria-hidden="true" tabindex="-1"></a>  <span class="at">values =</span> <span class="fu">c</span>(</span>
<span id="cb22-23"><a href="#cb22-23" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Very Low"</span> <span class="ot">=</span> <span class="st">"#2C7BB6"</span>,</span>
<span id="cb22-24"><a href="#cb22-24" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Low"</span> <span class="ot">=</span> <span class="st">"#ABD9E9"</span>,</span>
<span id="cb22-25"><a href="#cb22-25" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Moderate"</span> <span class="ot">=</span> <span class="st">"#FFFFBF"</span>,</span>
<span id="cb22-26"><a href="#cb22-26" aria-hidden="true" tabindex="-1"></a>    <span class="st">"High"</span> <span class="ot">=</span> <span class="st">"#FDAE61"</span>,</span>
<span id="cb22-27"><a href="#cb22-27" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Very High"</span> <span class="ot">=</span> <span class="st">"#D7191C"</span></span>
<span id="cb22-28"><a href="#cb22-28" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb22-29"><a href="#cb22-29" aria-hidden="true" tabindex="-1"></a>  <span class="at">na.value =</span> <span class="st">"grey90"</span>,</span>
<span id="cb22-30"><a href="#cb22-30" aria-hidden="true" tabindex="-1"></a>  <span class="at">name =</span> <span class="st">"Stunting Category"</span></span>
<span id="cb22-31"><a href="#cb22-31" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb22-32"><a href="#cb22-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-33"><a href="#cb22-33" aria-hidden="true" tabindex="-1"></a><span class="fu">labs</span>(</span>
<span id="cb22-34"><a href="#cb22-34" aria-hidden="true" tabindex="-1"></a>  <span class="at">title =</span> <span class="st">"Classification of Childhood Stunting Prevalence"</span>,</span>
<span id="cb22-35"><a href="#cb22-35" aria-hidden="true" tabindex="-1"></a>  <span class="at">subtitle =</span> <span class="st">"Country-level prevalence grouped into descriptive categories"</span>,</span>
<span id="cb22-36"><a href="#cb22-36" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">"Grey countries indicate that no prevalence data were available."</span></span>
<span id="cb22-37"><a href="#cb22-37" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb22-38"><a href="#cb22-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-39"><a href="#cb22-39" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">13</span>) <span class="sc">+</span></span>
<span id="cb22-40"><a href="#cb22-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-41"><a href="#cb22-41" aria-hidden="true" tabindex="-1"></a><span class="fu">theme</span>(</span>
<span id="cb22-42"><a href="#cb22-42" aria-hidden="true" tabindex="-1"></a>  <span class="at">panel.grid =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb22-43"><a href="#cb22-43" aria-hidden="true" tabindex="-1"></a>  <span class="at">axis.text =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb22-44"><a href="#cb22-44" aria-hidden="true" tabindex="-1"></a>  <span class="at">axis.title =</span> <span class="fu">element_blank</span>()</span>
<span id="cb22-45"><a href="#cb22-45" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Global_stunting_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="results" class="level1" data-number="10">
<h1 data-number="10"><span class="header-section-number">10</span> Results</h1>
<p>The analysis included <strong>162 countries</strong> with reported childhood stunting prevalence ranging from <strong>1.0%</strong> to <strong>55.3%</strong>. The mean prevalence was <strong>16.2%</strong>, while the median was <strong>11.7%</strong>, indicating that most countries reported relatively low to moderate prevalence, with a smaller number of countries experiencing substantially higher levels.</p>
<p>The histogram and boxplot demonstrated a positively skewed distribution, with Burundi identified as the only statistical outlier using the conventional 1.5 × IQR criterion. This finding indicates that although several countries experience elevated childhood stunting prevalence, extremely high values are uncommon within the dataset.</p>
<p>Ranking countries revealed considerable disparities in childhood nutritional outcomes. Burundi recorded the highest prevalence (55.3%), followed by Niger, Eritrea, Angola and Papua New Guinea. Conversely, Poland reported the lowest prevalence (1.0%), followed by Belarus, Estonia, Lithuania, the Netherlands, Tonga, Chile, Finland, Latvia and the Republic of Korea.</p>
<p>Spatial visualisation demonstrated clear geographical variation. Lower prevalence was generally observed across North America, Australia and much of Europe, whereas relatively higher prevalence was concentrated across several countries in West, Central, Eastern and Southern Africa. Additional areas of elevated prevalence were also observed in parts of Asia and Oceania.</p>
<p>The categorised choropleth map further highlighted these spatial differences by grouping countries into descriptive prevalence classes, allowing regions with comparatively high childhood stunting prevalence to be readily identified.</p>
</section>
<section id="discussion" class="level1" data-number="11">
<h1 data-number="11"><span class="header-section-number">11</span> Discussion</h1>
<p>This analysis demonstrates substantial variation in childhood stunting prevalence across countries, indicating that the burden of chronic childhood undernutrition is not evenly distributed worldwide. Both the statistical summaries and the spatial analyses consistently showed that relatively few countries account for the highest prevalence values, while many countries reported considerably lower levels.</p>
<p>The geographical clustering observed in the choropleth maps suggests that neighbouring countries often exhibit similar prevalence levels. Although this project was designed as a descriptive spatial analysis and therefore does not investigate causal relationships, the observed regional patterns provide a useful foundation for future studies examining socioeconomic, environmental and health-system determinants of childhood stunting.</p>
<p>The combination of descriptive statistics and GIS mapping illustrates how spatial analysis can improve understanding of global public health challenges by transforming numerical data into easily interpretable visual information.</p>
</section>
<section id="conclusion" class="level1" data-number="12">
<h1 data-number="12"><span class="header-section-number">12</span> Conclusion</h1>
<p>This project demonstrates a complete reproducible workflow for analysing and mapping childhood stunting prevalence using R, Quarto and Geographic Information Systems. Descriptive statistical analysis revealed considerable variability in childhood stunting prevalence across the 162 countries included in the dataset, while spatial visualisation highlighted clear geographical differences in disease burden.</p>
<p>The integration of statistical summaries with choropleth mapping provides an effective approach for communicating public health information and identifying areas experiencing comparatively high childhood stunting prevalence. Beyond the findings themselves, this project illustrates the value of reproducible analytical workflows for supporting transparent and evidence-based public health reporting.</p>
</section>
<section id="recommendations" class="level1" data-number="13">
<h1 data-number="13"><span class="header-section-number">13</span> Recommendations</h1>
<p>Future work could extend this analysis by:</p>
<ul>
<li>incorporating socioeconomic indicators such as gross domestic product, poverty rates or maternal education;</li>
<li>examining temporal trends using multi-year data;</li>
<li>performing spatial autocorrelation analyses (e.g., Moran’s I) to quantify geographical clustering;</li>
<li>developing predictive models using demographic and health indicators; and</li>
<li>conducting sub-national analyses where district or regional data are available.</li>
</ul>
</section>
<section id="appendix" class="level1" data-number="14">
<h1 data-number="14"><span class="header-section-number">14</span> Appendix</h1>
<section id="reproducibility-information" class="level2" data-number="14.1">
<h2 data-number="14.1" class="anchored" data-anchor-id="reproducibility-information"><span class="header-section-number">14.1</span> Reproducibility Information</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sessionInfo</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>R version 4.5.1 (2025-06-13 ucrt)
Platform: x86_64-w64-mingw32/x64
Running under: Windows 11 x64 (build 26200)

Matrix products: default
  LAPACK version 3.12.1

locale:
[1] LC_COLLATE=English_United States.utf8 
[2] LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

time zone: Africa/Lagos
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] scales_1.4.0      knitr_1.51        janitor_2.2.1     viridis_0.6.5    
 [5] viridisLite_0.4.3 sf_1.1-0          readxl_1.4.5      lubridate_1.9.4  
 [9] forcats_1.0.1     stringr_1.6.0     dplyr_1.2.1       purrr_1.2.0      
[13] readr_2.2.0       tidyr_1.3.2       tibble_3.3.0      ggplot2_4.0.2    
[17] tidyverse_2.0.0  

loaded via a namespace (and not attached):
 [1] utf8_1.2.6         generics_0.1.4     class_7.3-23       KernSmooth_2.23-26
 [5] stringi_1.8.7      hms_1.1.4          digest_0.6.39      magrittr_2.0.4    
 [9] evaluate_1.0.5     grid_4.5.1         timechange_0.3.0   RColorBrewer_1.1-3
[13] fastmap_1.2.0      cellranger_1.1.0   jsonlite_2.0.0     e1071_1.7-17      
[17] DBI_1.3.0          gridExtra_2.3      cli_3.6.5          rlang_1.2.0       
[21] units_1.0-1        withr_3.0.2        yaml_2.3.10        otel_0.2.0        
[25] tools_4.5.1        tzdb_0.5.0         vctrs_0.7.3        R6_2.6.1          
[29] proxy_0.4-29       lifecycle_1.0.5    classInt_0.4-11    snakecase_0.11.1  
[33] htmlwidgets_1.6.4  pkgconfig_2.0.3    pillar_1.11.1      gtable_0.3.6      
[37] Rcpp_1.1.0         glue_1.8.0         xfun_0.54          tidyselect_1.2.1  
[41] rstudioapi_0.18.0  farver_2.1.2       htmltools_0.5.8.1  labeling_0.4.3    
[45] rmarkdown_2.31     compiler_4.5.1     S7_0.2.1          </code></pre>
</div>
</div>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>