name: Link Check

on:
  pull_request:

jobs:
  links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@v2
        continue-on-error: true
        with:
          args: --verbose --no-progress --accept 200,403,429 "./*.html"
